# Generated by Django 5.2.4 on 2025-07-14 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kependudukan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(help_text='Deskripsi singkat atau persyaratan untuk surat ini.')),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_tracking', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('keperluan', models.TextField()),
                ('status', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=50)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('jenis_surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan_surat.jenissurat')),
                ('pemohon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kependudukan.warga')),
            ],
        ),
    ]
