# Generated by Django 5.2.4 on 2025-07-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='galeri/')),
            ],
        ),
        migrations.CreateModel(
            name='PotensiDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kategori', models.CharField(choices=[('Wisata', 'Wisata'), ('UMKM', 'UMKM')], max_length=50)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(upload_to='potensi_desa/')),
            ],
        ),
    ]
